### ISSUE TITLE
Uable to connect rabbitmq without localhost using nodejs

### ISSUE THREAD

**Issue by PreethiBabu87** [cloudamqp/nodejs-amqp-example#1]
Hi

am trying to connect rabbitmq in remote host using nodejs. But if i give 'amqp://localhost' it works.
If i give a specific hostname it doesnt.
Please find the code below. Kindly help:

The console output is blank. If got connected it should have displayed the message "AMQP connected".
This works with localhost.

amqp.connect('amqp://username:password@hostname:15672/', function (err, conn) {
        console.log(conn)
        if (err) {
            console.error("[AMQP]", err.message);
            return setTimeout(start, 1000);
        }
        conn.on("error", function (err) {
            if (err.message !== "Connection closing") {
                console.error("[AMQP] conn error", err.message);
            }
        });
        conn.on("close", function () {
            console.error("[AMQP] reconnecting");
            return setTimeout(start, 1000);
        });
        console.log("[AMQP] connected");
        amqpConn = conn;
        whenConnected();
    });

**Comment by PreethiBabu87** [comment]
Got the above issue rectified by chnaging the port number as 5672. But can anyone tell me how to add multiple hosts in the amqp connection string like we do in C#

"host=a.nam.nsroot.net,b.nam.nsroot.net,c.nam.nsroot.net,d.nam.nsroot.net,e.nam.nsroot.net;username=xxx;password=password;prefetchcount=50" />

**Comment by dentarg** [comment]
Multiple hosts isn't supported by amqplib: https://github.com/squaremo/amqp.node/issues/319

However, there's another library, called rascal, that supports it: https://github.com/guidesmiths/rascal#cluster-connections
