### ISSUE TITLE
How to pass cluster connection string?

### ISSUE THREAD

**Issue by nitinsinghit** [cloudamqp/nodejs-amqp-example#21]
I am trying 
var amqp_url = process.env.CLOUDAMQP_URL || ["amqp://admin:admin@172.26.1.2:5672/vhost_test","amqp://admin:admin@172.26.1.2:5672/vhost_test","amqp://user:pass@172.26.2.1:5672/vhost_test"];

**Comment by dentarg** [comment]
Looks like https://github.com/squaremo/amqp.node only support one server address. If you are not using the `CLOUDAMQP_URL` environment variable, you can set it like this

```javascript
var amqp_url = 'amqp://admin:admin@172.26.1.2:5672/vhost_test';
```

```javascript
// alternative if you still want to be able to use the environment variable
var amqp_url = process.env.CLOUDAMQP_URL || 'amqp://admin:admin@172.26.1.2:5672/vhost_test';
```

**Comment by nitinsinghit** [comment]
> Looks like https://github.com/squaremo/amqp.node only support one server address. If you are not using the `CLOUDAMQP_URL` environment variable, you can set it like this
> 
> ```js
> var amqp_url = 'amqp://admin:admin@172.26.1.2:5672/vhost_test';
> ```
> 
> ```js
> // alternative if you still want to be able to use the environment variable
> var amqp_url = process.env.CLOUDAMQP_URL || 'amqp://admin:admin@172.26.1.2:5672/vhost_test';
> ```

You mean only support single node not cluster?

**Comment by dentarg** [comment]
You can still use a cluster with multiple nodes, just that the client will only connect to one of the nodes.

**Comment by nitinsinghit** [comment]
> You can still use a cluster with multiple nodes, just that the client will only connect to one of the nodes.

How the connection string looks for multiple nodes? and on failure of one of the node does this library retries to connect to new master?

**Comment by dentarg** [comment]
There's no connection string for multiple nodes. I don't think it does, you can search the issues or ask at https://github.com/squaremo/amqp.node
